/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoLlegarRouteImport } from './routes/como-llegar'
import { Route as ConsejosRouteImport } from './routes/consejos'
import { Route as DondeDormirRouteImport } from './routes/donde-dormir'
import { Route as QueVerYHacerRouteImport } from './routes/que-ver-y-hacer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoLlegarRoute = ComoLlegarRouteImport.update({
  id: '/como-llegar',
  path: '/como-llegar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsejosRoute = ConsejosRouteImport.update({
  id: '/consejos',
  path: '/consejos',
  getParentRoute: () => rootRouteImport,
} as any)
const DondeDormirRoute = DondeDormirRouteImport.update({
  id: '/donde-dormir',
  path: '/donde-dormir',
  getParentRoute: () => rootRouteImport,
} as any)
const QueVerYHacerRoute = QueVerYHacerRouteImport.update({
  id: '/que-ver-y-hacer',
  path: '/que-ver-y-hacer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-llegar': typeof ComoLlegarRoute
  '/consejos': typeof ConsejosRoute
  '/donde-dormir': typeof DondeDormirRoute
  '/que-ver-y-hacer': typeof QueVerYHacerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-llegar': typeof ComoLlegarRoute
  '/consejos': typeof ConsejosRoute
  '/donde-dormir': typeof DondeDormirRoute
  '/que-ver-y-hacer': typeof QueVerYHacerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-llegar': typeof ComoLlegarRoute
  '/consejos': typeof ConsejosRoute
  '/donde-dormir': typeof DondeDormirRoute
  '/que-ver-y-hacer': typeof QueVerYHacerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/como-llegar' | '/consejos' | '/donde-dormir' | '/que-ver-y-hacer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/como-llegar' | '/consejos' | '/donde-dormir' | '/que-ver-y-hacer'
  id:
    | '__root__'
    | '/'
    | '/como-llegar'
    | '/consejos'
    | '/donde-dormir'
    | '/que-ver-y-hacer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoLlegarRoute: typeof ComoLlegarRoute
  ConsejosRoute: typeof ConsejosRoute
  DondeDormirRoute: typeof DondeDormirRoute
  QueVerYHacerRoute: typeof QueVerYHacerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-llegar': {
      id: '/como-llegar'
      path: '/como-llegar'
      fullPath: '/como-llegar'
      preLoaderRoute: typeof ComoLlegarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consejos': {
      id: '/consejos'
      path: '/consejos'
      fullPath: '/consejos'
      preLoaderRoute: typeof ConsejosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donde-dormir': {
      id: '/donde-dormir'
      path: '/donde-dormir'
      fullPath: '/donde-dormir'
      preLoaderRoute: typeof DondeDormirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/que-ver-y-hacer': {
      id: '/que-ver-y-hacer'
      path: '/que-ver-y-hacer'
      fullPath: '/que-ver-y-hacer'
      preLoaderRoute: typeof QueVerYHacerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoLlegarRoute: ComoLlegarRoute,
  ConsejosRoute: ConsejosRoute,
  DondeDormirRoute: DondeDormirRoute,
  QueVerYHacerRoute: QueVerYHacerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
